// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-LFE4bqwv8HtJBkUT4E0nwrY6LT9HbD4',
    appId: '1:163566901003:web:2fa8934132ff69b13e340e',
    messagingSenderId: '163566901003',
    projectId: 'loc-6-overload-oblivion',
    authDomain: 'loc-6-overload-oblivion.firebaseapp.com',
    storageBucket: 'loc-6-overload-oblivion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxrB53iUNDPGtdbHFWvLtLmP-6rYO966I',
    appId: '1:163566901003:android:d067bcb761361f7b3e340e',
    messagingSenderId: '163566901003',
    projectId: 'loc-6-overload-oblivion',
    storageBucket: 'loc-6-overload-oblivion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Ci1LModzbt-4NbLglCBVH4s6VsJ8VBQ',
    appId: '1:163566901003:ios:129254c9d71ea2433e340e',
    messagingSenderId: '163566901003',
    projectId: 'loc-6-overload-oblivion',
    storageBucket: 'loc-6-overload-oblivion.appspot.com',
    iosBundleId: 'com.example.loc6OverloadOblivion',
  );
}
